# Template PHP Build

# This template allows you to validate your PHP application.
# The workflow allows running tests and code linting on the default branch.


image: lorisleiva/laravel-docker:8.0

pipelines:
  default:
    - parallel:
        - step:
            name: Test
            script:
              - composer install --ignore-platform-reqs
              - cp .env.example .env              
              - php artisan key:generate
              - ./vendor/bin/phpunit
            caches:
              - composer